export default {
    longitud:4,
    tomatico:["Hola Wenge, se que eres nueva en la ciudad \npero no es excusa para ser una vaga",
    "es momento de que te pongas a trabajar,\nasi que ENHORABUENA ahora trabajas para \n PLOVOO",
    "Tienes que llevar los encargos que te \nhagan a su dueño ",
    "RECUERDA; A y D para moverte, no es complicado,\nsi los tratas bien y les contestas como quieren\n seguro que te dan propina"],
    tomatico_fin:["Holi, UwU, ya me estaba entrando hambre\n¿Los macarrones tienen tomatico?",
    "esto de la revolución me da un poco de miedo",
    "Aparentemente la gente esta harta de trabajar,\nson comunistas ahora,\nno se,mientras me dejen twitear",
    "ya sabes, responsabilidad afectivad,frases\n profundas fingir ser activista por los\n derechos humanos... !Deberías hacerte twiter¡"
    ],
    tomatico_fin_a:["Obvio","¿Qué\n revolución?","claro","!Claro¡\nme lo haré"],
    tomatico_fin_b:["no...","¿Qué\n revolución?","no se que\n es twitear","Ni en\n broma"],
    tomatico_fin_comprueba_a:[false,false,false,false],
    tomatico_fin_comprueba_b:[true,false,true,true],
    
    Manzanilla:["Buenas Wengi, tu última entrega fue algo \n peculiar  tampoco hacia falta que \n fueras en sentido contrario a los coches", 
    "pero tampoco me preocupa",
    "Ahora tienes que entregar al presidente del \n gobierno una manzanilla,  ya sabes que está\n agobiado con esto de la revuelta comunista" 
    ,"no hay nadie mejor que tu para esto, \n(no hay nadie más)"],
    Manzanilla_fin:["Wenga, Muchas gracias por la manzanilla, \n sin animo de lucro estoy un poco agobiado \ncon esto de las revueltas",
    "¿Quién me iba a decir que si les quitaba \nel derecho a huelga se iban a quejar?",
    "Tú, que eres una buena trabajadora lo entenderás,\nahí, dando el cayo y no recurriendo\n a subvenciones",
    "perdona me tengo que ir que tengo una reunión\n con ¿Quién era, Patry Puncha? ",
    ],
    Manzanilla_fin_a:["*guardar\nsilencio*"," Que fuerte\nme parece","Como tiene\nque ser","No me suena"],
    Manzanilla_fin_b:["*guardar\nsilencio*","solo quieren\n derechos","no se que\nes una\nsubvencion","¿La novia\n de Cisco?"],
    Manzanilla_fin_comprueba_a:[false,false,false,true],
    Manzanilla_fin_comprueba_b:[false,true,true,true],
    Aceite:["Buenas Wagira, hoy tienes una entrega un tanto\n peculiar, se ve que una -influencer- ha sacado\n un  disco de moteros y los tiene a todos\n derrapando",
    "Ten cuidado. Para la entrega de hoy tendrás\n que llevarle aceite de carro, además,\n hay mucho motero suelto",
    "y no se si has visto las noticias pero \n la reunión de ayer del Presi fue regu.\nEstos comunistas...ya está bien tanto pedir...",
    "si te encarga algo más ya puedes tratarlo bien"],
    Aceite_fin:["Oh,¿El personal de limpieza?",
    "AYY, perdoname,tienes pinta...\n¿Le has dado like a mi último TikTok?",
    "Una verdadera Motomami nunca le dice que no a\n una vueltecita o como yo le llamo,\n un teteo",
    "Saoko papi Saoko"],
    Aceite_fin_a:["¿coña?","SII","soy una \nmotomami"," MOTOMAMI\nAOTY"],
    Aceite_fin_b:["no","A de Alfa,\naltura\nalien","¿Moto-que?","MOTOMAMI\nFLOP"],
    Aceite_fin_comprueba_a:[false,true,false,false],
    Aceite_fin_comprueba_b:[true,true,true,true],
    Croquetas:["Hola Dengue, me temo que se vienen curvas,\nentre que es de noche y la revuelta comunista,\n la gente se está volviendo loca ",
    "una vez mas el increible personal de KULENGA STUDIOS\n está trasnochando para terminar una entrega,\n de ¿PUBLI? algo así",
    "Llevales unas croqueticas que están esmayaos\n los pobres",
    "El grupo comunista liderado por PatryRuncha\n y Raemoncín anda suelto, ten muhco cuidado"],
    Croquetas_fin:["Buenas, yo soy Sheila, tú eras Wakanda ¿no?\n como la peli jiji",
    "Traes las croquetas ¿verdad?\n muchas gracias reina chechewa",
    "Wakanda forever amor",
    "¿Pero solo 15 crequetas?¿Te has comido el resto?"],
    Croquetas_fin_a:["Sí, claro","Malawi es\nrepublicana...","Me encanta\nesa serie","Sí"],
    Croquetas_fin_b:["No...","Sí soy","¿Ein?","No"],
    Croquetas_fin_comprueba_a:[false,true,false,true],
    Croquestas_fin_comprueba_b:[true,false,true,false],
    Arsenico:["Buenas yo soy Patry Runcha, líder del \npartido comunista, nos hemos dado cuenta que\n tienes una relación muy cercana  con el\n presidente",
    "Eres su repartidora de Ploboo,\nWenge, vengo a pedirte algo muy serio,\nsi estas cansada de ser tu propia jefa\neste es el momento",
    "El Presi te ha pedido su típica manzanilla pero\nesta vez, si quieres,\nsólo si tu quieres,\nla podemos aliñar",
    "Efectivamente, con arsénico, que se acabe el\n yugo  del capitalismo en este pais y\n por fin el proletario tenga lo que se merece, \n el poder"],
    Arsenico_fin:["Hola Wikiri \n sigo un poco agobiado con todo esto \ncon humanidad y democracia nunca\nhan sido libreados los pueblos",
    "Ahora me piden el derecho a voto ¿esto que es?",
    "Soberania nacional, derecho a huelga, división\n de poderes... cariño,\n NO soy una constitución y ni la van a tener",
    "Que falta me hace una manzanilla \n ¿La tienes?"],
    Arsenico_fin_a:["¿Wikiri?\n¿enserio?","No se lo que\nes votar","¿Consti-que?","Sí claro"],
    Arsenico_fin_b:["Sí soy","Tiene\nsentido","Solo quieren\nderechos","No"],
    Arsenico_fin_comprueba_a:[true,false,true,true],
    Arseico_fin_comprueba_b:[false,true,false,false],

 

}