export default {
    longitud:4,
    tomatico:["Hola Wenge, se que eres nueva en la ciudad \n peor no es excusa pa ser una vaga",
    "es momento de que te pongas a trabajar,\n asi que ENHORABUENA ahora trabajas para \n PLOVOO",
    "Tienes que llevar los encargos que te \n hagan a su dueño ",
    "RECUERDA; A y D para moverte, no es complicado"],
    tomatico_fin:["Holi, UwU, ya me estaba entrando hambre",
    "responsabilida afectiva",
    ". y digo si me lio",
    "me siento solo ¿me das mimos?"
    ],
    tomatico_fin_a:["totalmente","no","no","venga"],
    tomatico_fin_b:["si","no","si","venga"],
    tomatico_fin_comprueba_a:[true,false,true,false],
     tomatico_fin_comprueba_b:[false,false,false,false],
    
    Manzanilla:["Buenas Wengi, tu última entrega fue algo \n peculiar  tampoco hacia falta que \n fueras en sentido contrario", 
    "pero tampoco me preocupa",
    "Ahora tienes que entregar al presidente del \n gobierno una manzanilla,  ya sabes que está\n agobiado con esto de la revuelta comunista" 
    ,"no hay nadie mejor que tu para esto, \nNO HAGAS PREGUNTAS"],
    Manzanilla_fin:["Wenga, Muchas gracias por la manzanilla, \n sin animo de lucro estooy un poco agobiado \n con esto de las revueltas",
    "¿Quien me iba a decir que si les quitaba \n el derecho a huelga se iban a quejar?",
    "Tu, que eres una buena trabajadora lo entenderás,\n ahí, dando el cayo y no recurriendo\n a subvenciones",
    "perdona me tengo que ir que tengo una reunión\n con ¿Quién era, Patry Puncha? ",
    ],
    Manzanilla_fin_a:["*guardar\nsilencio*"," Que fuerte\nme parece"," hmmm"," Adios <3"],
    Manzanilla_fin_b:["*guardar\nsilencio*","solo quieren\n derechos","no se que\nes una\nsubvencion"," Adios <3"],
    Manzanilla_fin_comprueba_a:[false,true,false,true],
    Manzanilla_fin_comprueba_b:[false,false,true,true],
    Aceite:["Buenas Wagira, hoy tienes una entrega un tanto\n peculiar, se ve que una -influencer- ha sacado\n un  disco de moteros y los tiene a todos\n derrapando",
    "Ten cuidado que para la entrega de hoy tendrás\n que llevarle aceite de carro y\n hay mucho motero suelto",
    "y no se si has visto las noticias pero \n la reunión de ayer del Presi fue regu",
    "si te encarga algo más ya puedes tratarlo bien"],
    Aceite_fin:["Oh,¿El personal de limpieza?",
    "AYY, perdoname, es que te veia tan oscurita... \nTienes el aceite de carro,¿no?",
    "Una verdadera Motomami nunca le dice que no a\n una vueltecita o como yo le llamo,\n un teteo",
    "Saoko pai Saoko"],
    Aceite_fin_a:["¿coña?","Sí","brum brum"," MOTOMAMI\nAOTY"],
    Aceite_fin_b:["no","honestamente, me lo bebí","¿Moto-que?","MOTOMAMI\nFLOP"],
    Aceite_fin_comprueba_a:[true,true,true,true],
    Aceite_fin_comprueba_b:[false,false,false,false],
    Croquetas:["Hola Dengue, me temo que se vienen curvas,\n entre que es de noche y la revuelta comunista\n esta    la gente se está volviendo loca ",
    "una vez mas el increible personal de KULENGA STUDIOS\n está trasnochando para terminar una entraga,\n de ¿PUBLI? algo asi",
    "Llevales unas croqueticas que estan esmayaos\n los pobres",
    "Cuidado que los coches explotan"],
    Croquetas_fin:["Buenas, yo soy Sheila tu eras Wakanda ¿no?\n como la peli jiji",
    "Traes las croquetas ¿verdad?\n muchas gracias reina Malawi",
    "Wakanda forever amor",
    "Toma cogete una, espera ¿Puedes comer jamón?\n Puff que bocadillo me voy a hacer"],
    Croquetas_fin_a:["Si, claro","Malawi es\nrepublicana...","Me encanta\nesa serie","Sí"],
    Croquetas_fin_b:["No...","Sí soy","¿Ein?","No"],
    Croquetas_fin_comprueba_a:[true,false,true,true],
    Croquestas_fin_comprueba_b:[false,true,false,false],
    Arsenico:["Buenas yo soy Patry Runcha, lider del \npartido comunista, nos hemos dado cuenta que\n tienes una relación muy cercana  con el\n presidente",
    "Eres su repartidora de Plovoo,\nWenge, vengo a pedirte algo muy serio,\nsi estas cansada de ser tu propia jefa\neste es el momento",
    "El Presi te ha pedido su típica manzanilla pero\nesta vez, si quieres,\nsólo si tu quieres,\nla podemos aliñar",
    "Efectivamente, con arsénico, que se acabe el\n yugo  del capitalismo en este pais y\n por fin el proletario tenga lo que se merece, \n el poder"],
    Arsenico_fin:["Hola Wikiri \n sigo un poco agobiado con todo esto",
    "Ahora me piden el derecho a voto ¿esto que es?",
    "Soberania nacional, derecho a huelga, división\n de poderes... cariño,\n NO soy una constitución y ni la van a tener",
    "Que falta me hace una manzanilla \n ¿La tienes?"],
    Arsenico_fin_a:["¿Wikiri?\n¿enserio?","No se lo que\nes votar","¿Consti-que?","Sí claro"],
    Arsenico_fin_b:["Y como pa no,\nme la bebí","Tiene\nsentido","Solo quieren\nderechos","No"],
    Arsenico_fin_comprueba_a:[false,true,true,true],
    Arseico_fin_comprueba_b:[true,false,false,false],

 

}